version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/terms-explainer:latest .

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USERNAME/terms-explainer:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
